// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpGtsWb6g3iT1M0khAaVW_av59Tt5_ZA',
    appId: '1:806070159000:web:74f5cac9139a49e0c0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    authDomain: 'attendance-app-55b40.firebaseapp.com',
    storageBucket: 'attendance-app-55b40.appspot.com',
    measurementId: 'G-QXGRKNR9R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAzldC3_a1p980hSYikB-_vpRhyD3eLQ',
    appId: '1:806070159000:android:b04846ef0abdacfec0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    storageBucket: 'attendance-app-55b40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6URuYGVhHS3uJh8Yle-eJjUzwbnyPb7w',
    appId: '1:806070159000:ios:8cd0bc4675ccfa9ec0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    storageBucket: 'attendance-app-55b40.appspot.com',
    iosBundleId: 'com.example.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6URuYGVhHS3uJh8Yle-eJjUzwbnyPb7w',
    appId: '1:806070159000:ios:8cd0bc4675ccfa9ec0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    storageBucket: 'attendance-app-55b40.appspot.com',
    iosBundleId: 'com.example.manager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJpGtsWb6g3iT1M0khAaVW_av59Tt5_ZA',
    appId: '1:806070159000:web:47d720804ecf1853c0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    authDomain: 'attendance-app-55b40.firebaseapp.com',
    storageBucket: 'attendance-app-55b40.appspot.com',
    measurementId: 'G-88D53VPB6V',
  );
}
