import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:manager/screens/manager_login_page.dart';
import 'package:manager/screens/manager_dashboard.dart';
import 'package:manager/screens/Manager_Profile_Setup.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(ManagerApp());
}

class ManagerApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Manager App',
      initialRoute: '/login',
      routes: {
        '/login': (context) => ManagerLoginPage(),
        '/managerDashboard': (context) => ManagerDashboard(),
        '/managerProfileSetup':(context) => ManagerProfileSetupPage(),
      },
    );
  }
}
