import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:manager/screens/manager_login_page.dart';
import 'package:manager/screens/manager_dashboard.dart';
import 'package:manager/screens/Manager_Profile_Setup.dart';
import 'package:manager/screens/edit_manager_profile.dart';
import 'package:manager/SplashScreen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static const String loginRoute = '/login';
  static const String managerProfileSetupRoute = '/managerProfileSetup';
  static const String managerDashboardRoute = '/managerDashboard';
  static const String editManagerProfileRoute = '/editManagerProfile';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Manager Dashboard',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:SplashScreen(),
      //initialRoute: loginRoute, 
      routes: {
        loginRoute: (context) => ManagerLoginPage(),
        managerProfileSetupRoute: (context) => ManagerProfileSetupPage(),
        managerDashboardRoute: (context) => ManagerDashboard(),
        editManagerProfileRoute: (context) => EditManagerProfilePage(),
      },
    );
  }
}